import Head from 'next/head';
import ThemeMode from "../components/Switch";
import GlobalStyle from '../styles/GlobalStyle';

export default function Home() {
	return (
		<>
			<Head>
				<title>Ginie&apos;s Portfolio</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<GlobalStyle />
      <ThemeMode />
		</>
	);
}
